[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  publish = "."
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[functions."katago-move"]
  timeout = 26

[functions."game-summary"]
  timeout = 26

[functions."analyze-move"]
  timeout = 26
